### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by llihku** [ai4ce/DeepMapping2#5]
Dear authors, 
Thank you for your great work and open-sourced code. When training this model using './run_train.sh', I encountered torch.cuda.OutOfMemoryError (My device is RTX2080Ti with 11GB memory). What is the memory requirement of this model given the default parameters? Any suggestions on reducing the model size or adaption to multi-GPU training? Thanks in advance.

**Comment by Gaaaavin** [comment]
Hi llihku. For the default setting, it is expected to use ~14GB of CUDA memory. 
You can reduce `$N` or `G_SIZE` to fit the model and data in your case, but do note this might affect the performance or accuracy of the model.

**Comment by llihku** [comment]
> 

Thanks for your suggestion. It works.

**Comment by llihku** [comment]
> Hi llihku. For the default setting, it is expected to use ~14GB of CUDA memory. You can reduce `$N` or `$G_SIZE` to fit the model and data in your case, but do note this might affect the performance or accuracy of the model.

Thanks for your suggestion. It works.
