### ISSUE TITLE
Convergence with KITI dataset after 50 epochs and default parameters

### ISSUE THREAD

**Issue by DineshchandarR** [ai4ce/DeepMapping2#6]
Dear authors,
At the outset, I would like to thank you for sharing your work and open-source the code. 
While training this model using 'run_train.sh' with default parameters for  KITI dataset, but even after 50 epochs, the network is not converging. Is there something I am missing, or are there other hyperparameters we need to use to get the results.

Thanks for your time and assistance.

**Comment by Gaaaavin** [comment]
Hi DineshchandarR. Thank you for your interest.
We noticed there can be some issues directly installing the dependencies from `requirements.txt`. We think one alternative is to install the dependencies individually.

After you create the environment, first install pytorch by
```
pip install torch==1.13.1 --index-url https://download.pytorch.org/whl/cu118
```
Then, install other dependencies by
```
pip install open3d==0.16.0 numpy matplotlib tqdm
```
Hope this can solve the problem.

**Comment by Gaaaavin** [comment]
We've just updated `requirements.txt`. It should solve the problem.
