### ISSUE TITLE
Training for 100 epochs with default parameters, but the model does not converge

### ISSUE THREAD

**Issue by liaoyifei1998** [ai4ce/DeepMapping2#7]
Dear Author
    Thanks for your great paper and source code. 
    Something wrong i have encountered is that training for 100 epochs with default parameters, but the model does not converge. I have tried the method you provided in this issue(https://github.com/ai4ce/DeepMapping2/issues/6), but it doesn't seem to work. The result i got is shown in followed figures. Is there something i missing, or could you please tell me some training tips of your work?

Thanks again.

![rotation_ate](https://user-images.githubusercontent.com/83771644/227906182-b4ad3e39-b842-4dac-a454-9708ed6bfe0a.png)
![training_loss](https://user-images.githubusercontent.com/83771644/227906189-d808eea3-75fa-444a-a97c-056f33121909.png)
![translation_ate](https://user-images.githubusercontent.com/83771644/227906192-970446e2-671b-4ec5-bb30-4ba74167323f.png)

**Comment by Gaaaavin** [comment]
If you followed the previous requirements, please make sure that you removed the environment and re-create a new one. Try `conda clean -a` if you make sure the installation is not affected by any cached packages.
After you install the dependencies following the up-to-date README file, please try `pip freeze` to make sure the installed dependency is the same as `requirements.txt` (you also should have torch==1.13.1+cu116)

**Comment by simbaforrest** [comment]
@liaoyifei1998 @Gaaaavin is this issue addressed?

**Comment by Gaaaavin** [comment]
Closed due to no further response. Please reopen if the problem is not solved.
