### ISSUE TITLE
Release of Optimization Results on KITTI 0018 and 0027 sequence

### ISSUE THREAD

**Issue by llihku** [ai4ce/DeepMapping2#9]
Dear authors,
Thank you for your great work and open-sourced code. Due to the limited configuration of my device, I cannot train the network with the default parameters, so I cannot obtain results as good as yours. Would you mind releasing the optimized trajectory (i.e. the final pose of each frame) on the KITTI 0018 and 0027 sequence (Corresponding to the DM2 results listed in Table 1. in the paper)? I just want to stack the point cloud together and visualize the map quality. Thank you!

**Comment by simbaforrest** [comment]
@Gaaaavin @Joechencc please take a look

**Comment by Gaaaavin** [comment]
@llihku One Google Drive link is added to the `results` folder in the recent [commit](https://github.com/ai4ce/DeepMapping2/tree/22366c02c4f9e8bacc67603195a41bbf05d9b3f2). The link contains the best mapping results (poses) reported in the paper.

**Comment by Joechencc** [comment]
Please follow this link https://github.com/Gaaaavin/DeepMapping2. We amended some version problems and tested under several environments. Now it should be ok. We will update this repo soon and provide more details of how to generate a custom group matrix and prior pose
